### ISSUE TITLE
Cache per object

### ISSUE THREAD

**Issue by ad-m** [dominicrodger/django-tinycontent#1]
Hello,

Thank you about useful package. What do you think about cache support? It looks it isn't very hard to implement it.  

Django-addendum support cache, but your package looks more promising.

Greetings,

**Comment by dominicrodger** [comment]
Thanks for filing @ad-m :)

Cache support sounds like a good idea. I'll get that done today, all going well.

**Comment by dominicrodger** [comment]
Sorry for the delay here - I've got this working, just need to find good ways to test this (i.e. to test that a given function call doesn't hit the database, but retrieves data from the cache). I'm hoping to be able to release 0.4.0 tomorrow with this feature.

**Comment by dominicrodger** [comment]
Fixed in d6725f156555d2116264864dcf50ac3e9f63a513. Turns out I'd already released 0.4.0, so this is in 0.5.0, which is now available on [PyPI](https://pypi.python.org/pypi/django-tinycontent).

**Comment by ad-m** [comment]
Changelog og
