### ISSUE TITLE
Lack of tests coverage report

### ISSUE THREAD

**Issue by ad-m** [dominicrodger/django-tinycontent#13]
This code is tested. I believe it will be good to show it to encourage propability include in awesome-django (see rosarior/awesome-django#142).

We can use coveralls.io for that.

Here is packages: https://coveralls.zendesk.com/hc/en-us/articles/201342869-Python 
Here is example: https://github.com/scibi/django-teryt/blob/master/.travis.yml

**Comment by dominicrodger** [comment]
Coverage is now posted to coveralls.io, and I've added the badge to the README.

Thanks @ad-m!
