### ISSUE TITLE
Remove live edit option

### ISSUE THREAD

**Issue by ymorin007** [dominicrodger/django-tinycontent#14]
Hi,

Thanks for this great plugin.  Can you tell if its possible to remove the option for the live edit.
![2016-04-21_1946](https://cloud.githubusercontent.com/assets/1857406/14727516/bc9b3dc2-07f9-11e6-921d-398d8dc254f6.png)

**Comment by dominicrodger** [comment]
It's not currently, no. I'd be happy to accept a pull request to either:

- Add an argument to the template tags to remove it; or
- Add a wrapper span around the link to make it easily removable with CSS.

**Comment by ad-m** [comment]
@ymorin007 , you can use https://github.com/dominicrodger/django-tinycontent/compare/master...watchdogpolska:edit_mode to start works. I don't have enough time to work on #7.

**Comment by dominicrodger** [comment]
Closing in favour of #7.
