### ISSUE TITLE
Caching with the name can cause warnings

### ISSUE THREAD

**Issue by ataylor32** [dominicrodger/django-tinycontent#19]
Since the `TinyContent` model's `get_cache_key` method uses the raw value of the `name` field, it's possible for it to generate warnings from [Django's `BaseCache` class' `validate_key` method](https://github.com/django/django/blob/1.10/django/core/cache/backends/base.py#L230-L247).

Using the `pk` field would prevent the warnings, but then the `TinyContent` model's `get_content_by_name` method would have to query the database to get the `pk` field, thus defeating the purpose of caching. You can't slugify the `name` field either because then you could end up with cache key collisions since two unique names could generate the same slug. I think the best approach is to use a fast, non-cryptographic hashing algorithm on the name.

**Comment by dominicrodger** [comment]
Thanks Adam. Technically you could end up with cache key collisions of you
hash too. Is there a reason to not just use ASCII names? I'm open to being
convinced, just not sure of the use case.

Dom

**Comment by dominicrodger** [comment]
One more thought - if we wanted to avoid cache key collisions, and have a cache-safe name, we could just base64 encode it (I think that's quite possibly what you had in mind, re-reading your post).

**Comment by ataylor32** [comment]
A space is one of the characters that trigger the warning, so a name such as "Homepage Intro" will trigger the warning.

As for how to go about hashing the name, base64 would work and it's one method that I thought about, but I don't know if it's the best choice (I'm not an expert in that area). There may be algorithms that are faster and generate shorter hashes that are still unique. It probably doesn't matter that much, though.

**Comment by ad-m** [comment]
URL encoding should be sufficient for that cases IMO. In was pretty was, unique (no collision like MD5) and increase of length only for weird characters.

**Comment by dominicrodger** [comment]
Fixed in 0.6.1, available now on PyPI.
