### ISSUE TITLE
Tags missing from GitHub repository

### ISSUE THREAD

**Issue by akaihola** [dominicrodger/django-tinycontent#22]
Currently, `v0.1.8` is the latest tag in the repository.

I'd like to browse the source for an old version – could you push tags for past versions?

**Comment by dominicrodger** [comment]
Hi @akaihola - you're welcome to do it, but I don't have time right now. You can browse the repository as of a given version (here's a [link for 0.6.0](https://github.com/dominicrodger/django-tinycontent/blob/bdb51474368cfd4c666e953e2a40bec19afed932/tinycontent/__init__.py), for example)
