### ISSUE TITLE
Changelog on PyPI

### ISSUE THREAD

**Issue by ad-m** [dominicrodger/django-tinycontent#6]
Hello,

I am would like report changelog on PyPI are outdated. See https://pypi.python.org/pypi/django-tinycontent/0.5.0 . It doesn't cover v5.0.

Please, take mind about properly tagging versions in git.

Greetings,

**Comment by dominicrodger** [comment]
Nice spot Adam :)

I spotted that after I pushed the release to PyPI. It'll be fixed when I release a new version, but I'm not sure it's worth pushing a new version to PyPI just to fix that.

People can pick up release notes from GitHub or https://django-tinycontent.readthedocs.org/en/latest/changelog.html#v0-5-0 for now.

**Comment by ad-m** [comment]
For future cases please add to bookmarks https://gist.github.com/audreyr/5990987 .
